version: "3.8"
services:
  apigateway:
    image: "jobhunterpad/job-hunter-api-gateway:latest"
    ports:
      - "8090:80"

  frontend:
    image: "jobhunterpad/job-hunter-frontend:latest"
    depends_on:
      - apigateway

  mongodb:
    image: "mongo"
    volumes:
      - ${MONGODB_BIND_MOUNT}:/data/db
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}
    ports:
      - "27017:27017"

  zookeeper:
    image: confluentinc/cp-zookeeper
    ports:
      - "2181:2181"
    volumes:
      - ${ZOOKEEPER_DATA_BIND_MOUNT}:/var/lib/zookeeper/data
      - ${ZOOKEEPER_LOGS_BIND_MOUNT}:/var/lib/zookeeper/log
    environment:
      - ZOOKEEPER_TICK_TIME=2000
      - ZOOKEEPER_CLIENT_PORT=2181

  kafka:
    image: confluentinc/cp-kafka
    ports:
      - "9092:9092"
    volumes:
      - ${KAFKA_BIND_MOUNT}:/var/lib/kafka/data
    environment:
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
    depends_on:
      - zookeeper

  authentication:
    image: "jobhunterpad/job-hunter-authentication:latest"
    depends_on:
      - kafka
  
  emailservice:
    image: "jobhunterpad/job-hunter-emailservice:latest"
    depends_on: 
      - kafka
