version: "3.8"
services:
  apigateway:
    image: "jobhunterpad/job-hunter-api-gateway"
    ports:
      - "8090:80"

  frontend:
    image: "jobhunterpad/job-hunter-frontend"
    depends_on:
      - apigateway

  mongodb:
    image: "mongo"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_PASSWORD}

  zookeeper:
    image: "bitnami/zookeeper"
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: "bitnami/kafka"
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper

volumes:
  mongo_data:
  zookeeper_data:
  kafka_data:
